### ISSUE TITLE
perkeepd: fresh build panics on startup

### ISSUE THREAD

**Issue by nf** [perkeep/perkeep#1136]
I just checked out perkeep at commit 0d960572015e1b9674b72f061297d077ce90bcbf, ran make.go, and then ran perkeepd, and this is what I get:

```
2018/05/01 08:47:28 Starting perkeepd version 2018-04-29-a4d0cc6ab7; Go go1.10.1 (freebsd/amd64)
2018/05/01 08:47:28 Starting to listen on http://localhost:3179
2018/05/01 08:47:28 ui: serving Closure from embedded resources
2018/05/01 08:47:28 Caught panic installer handlers: error instantiating storage for prefix "/bs/", type "blobpacked": largeBlobs at "/bs-packed/" of type *localdisk.DiskStorage doesn't support fetching sub-ranges of blobs
goroutine 1 [running]:
runtime/debug.Stack(0xc4200a8140, 0x2, 0xc42094a680)
        /home/nf/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /home/nf/go/src/runtime/debug/stack.go:16 +0x22
perkeep.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc42020dc80)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:548 +0x9e
panic(0xef97a0, 0xc42069e7b0)
        /home/nf/go/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc421032600, 0xc420fd2d00, 0x113dc8d, 0x4)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:309 +0x198
panic(0xef97a0, 0xc42069e7b0)
        /home/nf/go/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4210323f0, 0xc420fd2d00, 0x113d28d, 0x1)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:309 +0x198
panic(0xef97a0, 0xc42069e7b0)
        /home/nf/go/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4210327b0, 0xc420fd2d00, 0x115628c, 0x19)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:309 +0x198
panic(0xef97a0, 0xc42069e7b0)
        /home/nf/go/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc421032750, 0xc420fd2d00, 0x1148af7, 0xe)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:309 +0x198
panic(0xef97a0, 0xc42069e7b0)
        /home/nf/go/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4210326f0, 0xc420fd2d00, 0x113dc85, 0x4)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:309 +0x198
panic(0xef97a0, 0xc42069e7b0)
        /home/nf/go/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.exitFailure(0x1177d0d, 0x36, 0xc42020bc28, 0x3, 0x3)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:278 +0x167
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420fd2d00, 0x113dc85, 0x4)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:324 +0x3a0
perkeep.org/pkg/serverinit.(*handlerLoader).GetStorage(0xc420fd2d00, 0x113dc85, 0x4, 0x2, 0x2, 0x0, 0x0)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:252 +0x43
perkeep.org/pkg/blobserver/replica.newFromConfig(0x17953e0, 0xc420fd2d00, 0xc42100dda0, 0x7, 0xc4200e7740, 0xb500000000000001, 0x0)
        /home/nf/src/perkeep.org/pkg/blobserver/replica/replica.go:115 +0x26c
perkeep.org/pkg/blobserver.CreateStorage(0x114aa18, 0x7, 0x17953e0, 0xc420fd2d00, 0xc42100dda0, 0xe, 0x0, 0x0, 0x0)
        /home/nf/src/perkeep.org/pkg/blobserver/registry.go:111 +0xc3
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420fd2d00, 0x1148af7, 0xe)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:322 +0x25c
perkeep.org/pkg/serverinit.(*handlerLoader).GetStorage(0xc420fd2d00, 0x1148af7, 0xe, 0x113dc85, 0x4, 0xc42100cc90, 0x0)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:252 +0x43
perkeep.org/pkg/blobserver/cond.buildStorageForReceive(0x17953e0, 0xc420fd2d00, 0xf88560, 0xc42100de00, 0x0, 0x0, 0x0)
        /home/nf/src/perkeep.org/pkg/blobserver/cond/cond.go:134 +0x167
perkeep.org/pkg/blobserver/cond.newFromConfig(0x17953e0, 0xc420fd2d00, 0xc42100de30, 0x4, 0xc4200e7808, 0xc420204301, 0x0)
        /home/nf/src/perkeep.org/pkg/blobserver/cond/cond.go:90 +0x2b2
perkeep.org/pkg/blobserver.CreateStorage(0x1147800, 0x4, 0x17953e0, 0xc420fd2d00, 0xc42100de30, 0x19, 0x2, 0x4, 0xc42020c628)
        /home/nf/src/perkeep.org/pkg/blobserver/registry.go:111 +0xc3
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420fd2d00, 0x115628c, 0x19)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:322 +0x25c
perkeep.org/pkg/serverinit.(*handlerLoader).GetStorage(0xc420fd2d00, 0x115628c, 0x19, 0x0, 0x0, 0x0, 0x0)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:252 +0x43
perkeep.org/pkg/server.newRootFromConfig(0x17953e0, 0xc420fd2d00, 0xc42100d9b0, 0x4, 0xc4200be638, 0x0, 0x0)
        /home/nf/src/perkeep.org/pkg/server/root.go:121 +0xa7b
perkeep.org/pkg/blobserver.CreateHandler(0x113e431, 0x4, 0x17953e0, 0xc420fd2d00, 0xc42100d9b0, 0x1, 0x40, 0xc0, 0x40)
        /home/nf/src/perkeep.org/pkg/blobserver/registry.go:140 +0xc3
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420fd2d00, 0x113d28d, 0x1)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:371 +0xa39
perkeep.org/pkg/serverinit.(*handlerLoader).GetHandler(0xc420fd2d00, 0x113d28d, 0x1, 0x113d28d, 0x1, 0x0, 0x0)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:260 +0x43
perkeep.org/pkg/server.uiFromConfig(0x17953e0, 0xc420fd2d00, 0xc42100df20, 0x2, 0xc4200be590, 0xc421034001, 0xc420fe15c0)
        /home/nf/src/perkeep.org/pkg/server/ui.go:228 +0x5cf
perkeep.org/pkg/blobserver.CreateHandler(0x113d4ed, 0x2, 0x17953e0, 0xc420fd2d00, 0xc42100df20, 0x4, 0x0, 0x1, 0x30)
        /home/nf/src/perkeep.org/pkg/blobserver/registry.go:140 +0xc3
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420fd2d00, 0x113dc8d, 0x4)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:371 +0xa39
perkeep.org/pkg/serverinit.(*handlerLoader).setupAll(0xc420fd2d00)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:232 +0x92
perkeep.org/pkg/serverinit.(*Config).InstallHandlers(0xc420f7f5c0, 0x17841c0, 0xc42102e1e0, 0xc421017a20, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/nf/src/perkeep.org/pkg/serverinit/serverinit.go:617 +0xa0e
main.Main(0x0, 0x0)
        /home/nf/src/perkeep.org/server/perkeepd/camlistored.go:770 +0x4b5
main.main()
        /home/nf/src/perkeep.org/server/perkeepd/camlistored.go:713 +0x29
Error parsing config: Caught panic: error instantiating storage for prefix "/bs/", type "blobpacked": largeBlobs at "/bs-packed/" of type *localdisk.DiskStorage doesn't support fetching sub-ranges of blobs
```

**Comment by bradfitz** [comment]
I juuuuuust broke that.

Fixing.

**Comment by nf** [comment]
Can confirm this fixes the issue.
