### ISSUE TITLE
internal/osutil: non-hermetic use of config in test strikes again

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1161]
% go test ./server/perkeepd/
2018/05/11 23:54:56 Starting perkeepd version unknown; Go go1.10 (linux/amd64)
2018/05/11 23:54:56 Generating template config file /tmp/perkeepd-test530896302/fakeHome/conf/server-config.json
panic: Unexpected non-hermetic use of host configuration during testing. (alternatively: the 'testing' package got accidentally linked in)

goroutine 15 [running]:
perkeep.org/internal/osutil.failInTests()
	/home/mpl/src/perkeep.org/internal/osutil/paths.go:358 +0x85
perkeep.org/internal/osutil.HomeDir(0x1163aae, 0xf)
	/home/mpl/src/perkeep.org/internal/osutil/paths.go:38 +0x22
perkeep.org/internal/osutil.configDirNamed(0x115e614, 0xa, 0xc420365448, 0x1166002)
	/home/mpl/src/perkeep.org/internal/osutil/paths.go:198 +0xd9
perkeep.org/internal/osutil.perkeepConfigDir(0x202e360, 0xc42009ca50, 0x1166002, 0x11)
	/home/mpl/src/perkeep.org/internal/osutil/paths.go:172 +0x48
perkeep.org/internal/osutil.identitySecretRing(0x1166002, 0x11)
	/home/mpl/src/perkeep.org/internal/osutil/paths.go:259 +0x26
perkeep.org/internal/osutil.SecretRingFile(0x0, 0xc4203655a8)
	/home/mpl/src/perkeep.org/internal/osutil/paths.go:277 +0x75
perkeep.org/pkg/serverinit.getOrMakeKeyring(0xc420365790, 0x2, 0x2, 0xc422ee9840, 0x36, 0x5af61130)
	/home/mpl/src/perkeep.org/pkg/serverinit/genconfig.go:1283 +0x37
perkeep.org/pkg/serverinit.WriteDefaultConfigFile(0xc422ee97c0, 0x3c, 0xc420365c00, 0x1, 0x1)
	/home/mpl/src/perkeep.org/pkg/serverinit/genconfig.go:1263 +0x210
perkeep.org/server/perkeepd.loadConfig(0x0, 0x0, 0xc422e4ed20, 0x4, 0x4, 0x200fec0)
	/home/mpl/src/perkeep.org/server/perkeepd/camlistored.go:194 +0x3e0
perkeep.org/server/perkeepd.Main(0xc42021cf00, 0xc42021cf60)
	/home/mpl/src/perkeep.org/server/perkeepd/camlistored.go:941 +0x360
created by perkeep.org/server/perkeepd.TestStarts
	/home/mpl/src/perkeep.org/server/perkeepd/run_test.go:74 +0x5bc
FAIL	perkeep.org/server/perkeepd	0.235s

Introduced at rev 245bb63fff36ef0aacfec4c972b781a69adedf32

**Comment by mpl** [comment]
@bradfitz we can't cut the release until this one is fixed, as it went in the branch.

Let me know if you want to fix it (you probably know best since you "touched it last" ;) ), I'm looking into it until then.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/16306
