### ISSUE TITLE
Perkeepd panics on startup when using s3

### ISSUE THREAD

**Issue by kasisnu** [perkeep/perkeep#1170]
When setting up a fresh installation of perkeep, I ran in to the following panic.

```go/src/perkeep.org  master ✔                                                                                                                                      23h35m
▶ go run make.go && perkeepd                                                                                                                                              21:03:34
Success. Binaries are in /Users/kasisnu/go/bin
2018/05/17 21:03:45 Starting perkeepd version master, 2018-05-16-5789ec4b8d; Go go1.10.2 (darwin/amd64)
2018/05/17 21:03:45 Starting to listen on http://localhost:3179
2018/05/17 21:03:45 ui: serving Closure from embedded resources
2018/05/17 21:03:45 Caught panic installer handlers: error instantiating storage for prefix "/bs/", type "blobpacked": largeBlobs at "/bs-packed/" of type *proxycache.Storage does
n't support fetching sub-ranges of blobs
goroutine 1 [running]:
runtime/debug.Stack(0xc4200b2140, 0x2, 0xc422b680d0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/debug/stack.go:16 +0x22
perkeep.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc420747c88)
        /Users/kasisnu/go/src/perkeep.org/pkg/serverinit/serverinit.go:611 +0x9e
panic(0x1afd780, 0xc4200318d0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc420ceaba0, 0xc420ca8680, 0x1d425f2, 0x4)
        /Users/kasisnu/go/src/perkeep.org/pkg/serverinit/serverinit.go:303 +0x198
panic(0x1afd780, 0xc4200318d0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc420ceac00, 0xc420ca8680, 0x1d41bed, 0x1)
        /Users/kasisnu/go/src/perkeep.org/pkg/serverinit/serverinit.go:303 +0x198
panic(0x1afd780, 0xc4200318d0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc420ceadb0, 0xc420ca8680, 0x1d5ab43, 0x19)
        /Users/kasisnu/go/src/perkeep.org/pkg/serverinit/serverinit.go:303 +0x198
panic(0x1afd780, 0xc4200318d0)
        /usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc420cead50, 0xc420ca8680, 0x1d4d3fa, 0xe)
        /Users/kasisnu/go/src/perkeep.org/pkg/serverinit/serverinit.go:303 +0x198
panic(0x1afd780, 0xc4200318d0)```
```

It looks like `proxycache` doesn't implement `subFetcherStorage`. The bug was introduced in af4ecfb and versions prior appear to work fine.

**Comment by bradfitz** [comment]
I sent https://camlistore-review.googlesource.com/#/c/camlistore/+/16686

**Comment by kasisnu** [comment]
Thanks @bradfitz!
