### ISSUE TITLE
perkeepd: recovery didn't work

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1180]
```
dev:perkeep.org $perkeepd -reindex -recovery=2
2018/05/30 21:20:04 Starting perkeepd version master, 2018-05-19-d6c616c615; Go devel +3c4d3bdd3b Wed May 30 22:54:22 2018 +0000 (linux/amd64)
2018/05/30 21:20:04 Starting to listen on http://0.0.0.0:80 (for Let's Encrypt challenges)
2018/05/30 21:20:04 Starting to listen on https://localhost:4430
2018/05/30 21:20:05 Index wiped.
2018/05/30 21:20:05 Caught panic installer handlers: error instantiating storage for prefix "/bs/", type "blobpacked": failed to setup blobpacked metaIndex: error from "leveldb" KeyValue: file missing [file=MANIFEST-000000]
goroutine 1 [running]:
runtime/debug.Stack(0xc000030230, 0x2, 0xc002de8820)
        /home/bradfitz/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /home/bradfitz/go/src/runtime/debug/stack.go:16 +0x22
perkeep.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc0000d5c90)
```

Yes, that's why I was doing `-recovery`, because those files were missing. So don't crash on not being able to load them.

I nuked the directory more completely, and then it worked:

```
dev:perkeep.org $ rm -rf /mnt/bradpk/packed/packindex.leveldb/
dev:perkeep.org $ perkeepd -reindex -recovery=2
2018/05/30 21:20:37 Starting perkeepd version master, 2018-05-19-d6c616c615; Go devel +3c4d3bdd3b Wed May 30 22:54:22 2018 +0000 (linux/amd64)
2018/05/30 21:20:37 Starting to listen on http://0.0.0.0:80 (for Let's Encrypt challenges)
2018/05/30 21:20:37 Starting to listen on https://localhost:4430
2018/05/30 21:20:37 Starting recovery of blobpacked index
2018/05/30 21:20:50 blobpacked: 2017 / 97369 zip packs seen
2018/05/30 21:21:00 blobpacked: 4173 / 97369 zip packs seen
2018/05/30 21:21:10 blobpacked: 6382 / 97369 zip packs seen
2018/05/30 21:21:20 blobpacked: 8516 / 97369 zip packs seen
2018/05/30 21:21:30 blobpacked: 10652 / 97369 zip packs seen
2018/05/30 21:21:40 blobpacked: 12740 / 97369 zip packs seen
```

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/#/c/perkeep/+/16966

**Comment by lucaswilric** [comment]
I am experiencing this issue as well. I see that the change is waiting for review on Gerrit. Is there any info available on when that might get merged? Or anything I could do as a new-to-Go programmer to help it along?

**Comment by mpl** [comment]
@lucaswilric as a general rule, you can help by reviewing the change, and testing it. and asking more people to do the same. The more people have tried it, the more confident I can be merging it without waiting for Brad's review.
