### ISSUE TITLE
pkg/blobserver/s3 : test assertions fail because default instance is wrapped by a proxycache

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1189]
--- FAIL: TestS3WithBucketDir (0.10s)
panic: interface conversion: blobserver.Storage is *proxycache.Storage, not *s3.s3Storage [recovered]
	panic: interface conversion: blobserver.Storage is *proxycache.Storage, not *s3.s3Storage

goroutine 567 [running]:
testing.tRunner.func1(0xc42070a000)
	/home/mpl/go1/src/testing/testing.go:742 +0x29d
panic(0x6f24e0, 0xc4205a8840)
	/home/mpl/go1/src/runtime/panic.go:505 +0x229
perkeep.org/pkg/blobserver/s3.testStorage.func1(0xc42070a000, 0xc4202f4af0, 0x3, 0x2)
	/home/mpl/src/perkeep.org/pkg/blobserver/s3/s3_test.go:121 +0xb13

This happens because the s3 constructor now returns by default an s3Storage wrapped within a proxycache.Storage, as opposed to just an s3Storage before.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/17206 unblocks the situation for now by removing the proxycache. But we probably want to do better than that, as it is preferable to test the behavior of the package with its default initialization parameters (a 32MB cache).

**Comment by euank** [comment]
The test assertion failure is fixed on master with f92f9b80a3fb1f0a6e0623920315d895be54199e.

I think it's debatable whether we want to test with the proxycache's default value or not for the s3 blobserver in those tests.

My assumption was that the tests in the `blobserver/s3` package were meant to test the other code in that package, and similarly we could assume the proxy cache is tested separately.

We should still be integration testing the two packages together, but I would expect that code to exist in `pkg/test` somewhere instead.
