### ISSUE TITLE
Perkeepd not starting, level db seems to have been corrupted

### ISSUE THREAD

**Issue by verrol** [perkeep/perkeep#1320]
Hi all,

I have been using Perkeepd for a few years without issue. Typically, I start Perkeepd when I want to use it, and then stop it. However, recently I tried to start it and I got the message below.

I don't recall seeing an error or having any issues the last time I used it.

Please let me know how to resolve this or how to recover my data. Is it possible to start a new index or something?

Thanks,

.v

2020/09/20 11:54:24 Starting perkeepd version master, 2018-12-31-eb547718cb; Go go1.11.1 (darwin/amd64)
2020/09/20 11:54:24 Starting to listen on http://localhost:3179
2020/09/20 11:54:24 Caught panic installer handlers: error instantiating handler for prefix "/sync/", type "sync": error from "leveldb" KeyValue: open /Users/verrol/Perkeep/blobs/sync-to-index-queue.leveldb/CURRENT: input/output error
goroutine 1 [running]:
runtime/debug.Stack(0xc0000d0050, 0x2, 0xc000962620)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:16 +0x22
perkeep.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc000871c80)
	/Users/auser/go/src/perkeep.org/pkg/serverinit/serverinit.go:660 +0x9e
panic(0x1cef840, 0xc000e48e70)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc000e452f0, 0xc000db7260, 0x1f81560, 0x6)
	/Users/auser/go/src/perkeep.org/pkg/serverinit/serverinit.go:305 +0x196
panic(0x1cef840, 0xc000e48e70)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
perkeep.org/pkg/serverinit.exitFailure(0x1fc010c, 0x36, 0xc000871730, 0x3, 0x3)
	/Users/auser/go/src/perkeep.org/pkg/serverinit/serverinit.go:274 +0x15c
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc000db7260, 0x1f81560, 0x6)
	/Users/auser/go/src/perkeep.org/pkg/serverinit/serverinit.go:369 +0xb04
perkeep.org/pkg/serverinit.(*handlerLoader).setupAll(0xc000db7260)
	/Users/auser/go/src/perkeep.org/pkg/serverinit/serverinit.go:228 +0x92
perkeep.org/pkg/serverinit.(*Config).InstallHandlers(0xc000e46780, 0x2692f20, 0xc000e468c0, 0xc000e6c020, 0x15, 0x0, 0x0, 0x0, 0x0)
	/Users/auser/go/src/perkeep.org/pkg/serverinit/serverinit.go:727 +0x9cc
main.Main()
	/Users/auser/go/src/perkeep.org/server/perkeepd/perkeepd.go:455 +0x58c
main.main()
	/Users/auser/go/src/perkeep.org/server/perkeepd/perkeepd.go:391 +0x20
Error parsing config: Caught panic: error instantiating handler for prefix "/sync/", type "sync": error from "leveldb" KeyValue: open /Users/auser/Perkeep/blobs/sync-to-index-queue.leveldb/CURRENT: input/output error

**Comment by aviau** [comment]
Did you try to reindex/recover?

```
perkeepd -reindex -recover 2
```

**Comment by octaviordz** [comment]
Hi, I think I have a similar problem. In my case perkeepd does start up but when I do

> .\pk sync --src=http://localhost:3199/bs/  --dest=http://localhost:3199/index/

I get errors like:

> Destination needs blob: [sha224-b57ba554646d33364129c14271c33851cce978bd34cfdc18b2b05294; 5056 bytes]
> Destination needs blob: [sha224-d576c37cf9826330d7e7b13aa78134eb5064cbc60d0c1cadaf4540b9; 92012 bytes]
> 2023/04/25 09:46:33 Upload of sha224-d576c37cf9826330d7e7b13aa78134eb5064cbc60d0c1cadaf4540b9 to destination blobserver failed: corrupt blob; digest doesn't match
> 2023/04/25 09:46:39 Upload of sha224-b57ba554646d33364129c14271c33851cce978bd34cfdc18b2b05294 to destination blobserver failed: server didn't receive blob
> Error: sync failed: 5525 errors during sync

How I ended up here is by trying to sync to perkeep instances using:
> .\pk sync --src=http://localhost:3190/bs/  --dest=http://localhost:3199/bs/

And as far as I can tell that worked, at least perkeep doesn't report any errors or missing blobs even when running the sync command again. But on the web ui of the destination instance only a folder would show up and not it's content, expected result would be to see the folder and the files within the folder.


When running with options `-reindex -recovery 2` the output ends in:
> 2023/04/25 09:59:17 Reindexing at sha224-ff31b555b4a7e7c69f13612d683893fe4ad004bf3f548ec6565c9099
> 2023/04/25 09:59:18 Reindexing at sha224-ffaee80b51ca96e410b3e4298d6f690d078669c431395daaf134cc70
> 2023/04/25 09:59:19 Error reindexing /index/: 5525 blobs failed to re-index
> 2023/04/25 09:59:19 sync: /bs/ -> /index/: added 0 pending blobs from sync queue to pending list
> 2023/04/25 09:59:19 index/corpus: loading into memory...
> 2023/04/25 09:59:19 index/corpus: loading into memory... (1/10: meta rows)
> 2023/04/25 09:59:23 index/corpus: loaded prefix "meta": 316240 rows, 3.6537143s
> 2023/04/25 09:59:23 index/corpus: loaded prefix "signerkeyid": 1 rows, 0s
> 2023/04/25 09:59:23 index/corpus: loading into memory... (2/10: prefix "claim")
> 2023/04/25 09:59:23 index/corpus: loading into memory... (3/10: prefix "fileinfo")
> 2023/04/25 09:59:23 index/corpus: loading into memory... (4/10: prefix "filetimes")
> 2023/04/25 09:59:23 index/corpus: loading into memory... (5/10: prefix "imagesize")
> 2023/04/25 09:59:23 index/corpus: loading into memory... (6/10: prefix "wholetofile")
> 2023/04/25 09:59:23 index/corpus: loading into memory... (7/10: prefix "exifgps")
> 2023/04/25 09:59:23 index/corpus: loaded prefix "wholetofile": 0 rows, 0s
> 2023/04/25 09:59:23 index/corpus: loading into memory... (8/10: prefix "mediatag")
> 2023/04/25 09:59:23 index/corpus: loading into memory... (9/10: prefix "dirchild")
> 2023/04/25 09:59:23 index/corpus: loaded prefix "imagesize": 0 rows, 0s
> 2023/04/25 09:59:23 index/corpus: loaded prefix "mediatag": 0 rows, 0s
> 2023/04/25 09:59:23 index/corpus: loaded prefix "filetimes": 0 rows, 68.9654ms
> 2023/04/25 09:59:23 index/corpus: loaded prefix "exifgps": 0 rows, 68.9654ms
> 2023/04/25 09:59:23 index/corpus: loaded prefix "claim": 4 rows, 68.9654ms
> 2023/04/25 09:59:23 index/corpus: loaded prefix "fileinfo": 1 rows, 68.9654ms
> 2023/04/25 09:59:23 index/corpus: loaded prefix "dirchild": 2 rows, 68.9654ms
> 2023/04/25 09:59:23 index/corpus: stats: 47.772 MiB mem: 316240 blobs (18.412 GiB) (61596 schema (1 permanode, 1 file (0 image), ...)
> 2023/04/25 09:59:23 index/corpus: scanning CPU usage: 0s
> 

Hope someone can provide some pointers, something to check out. Thanks.

**Comment by tgulacsi** [comment]
"corrupt blob; digest doesn't match" - it seems that your files are corrupted.
