### ISSUE TITLE
Panic when git cloning from pk-mount

### ISSUE THREAD

**Issue by nagy** [perkeep/perkeep#1573]
Hello and thanks for this interesting project.

With a master build of just now and an empty and fresh `perkeepd` instance, I did the following.

I inserted a git repository like so:

```
pk-put file --permanode ~/my-git-repo
```

Then I mounted the store with:

```
mkdir /tmp/pk-mount
pk-mount /tmp/pk-mount
```

In another terminal I ran:

```
git clone /tmp/pk-mount/recent/my-git-repo
```

And got this output, while the clone got stuck:

```
2021/11/18 14:03:35 fuse: panic in handler for Lookup [ID=0x1c Node=0x4 Uid=1000 Gid=100 Pid=70184] "HEAD": nil context
goroutine 43 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0xa198d0, 0xc00012c600, 0xc0000bdeb0, 0xc0000bde0e)
	/home/user/go/pkg/mod/bazil.org/fuse@v0.0.0-20180421153158-65cc252bf669/fs/serve.go:857 +0x19e
panic(0x87e600, 0xa080f0)
	/nix/store/d4yf4kx2f8m0arh46p9llbhi74kgb2im-go-1.16.9/share/go/src/runtime/panic.go:965 +0x1b9
net/http.(*Request).WithContext(...)
	/nix/store/d4yf4kx2f8m0arh46p9llbhi74kgb2im-go-1.16.9/share/go/src/net/http/request.go:356
perkeep.org/pkg/client.(*Client).newRequest(0xc00022ca00, 0x0, 0x0, 0x930355, 0x3, 0xc000036380, 0x73, 0x0, 0x0, 0x0, ...)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/client/client.go:1229 +0x3ab
perkeep.org/pkg/client.(*Client).fetchVia(0xc00022ca00, 0x0, 0x0, 0xa1d100, 0xc000038180, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/client/get.go:99 +0x478
perkeep.org/pkg/client.(*Client).Fetch(0xc00022ca00, 0x0, 0x0, 0xa1d100, 0xc000038180, 0xd0, 0xd0, 0x7faef7428108, 0xd0, 0xc0000b45b0)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/client/get.go:49 +0xa9
perkeep.org/pkg/cacher.(*CachingFetcher).faultIn.func1(0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/cacher/cacher.go:85 +0xb1
go4.org/syncutil/singleflight.(*Group).Do(0xc0001d2a68, 0xc00002a440, 0x3f, 0xc0000bd678, 0xc0001d29c0, 0x0, 0x0, 0xa1d100)
	/home/user/go/pkg/mod/go4.org@v0.0.0-20190218023631-ce4c26f7be8e/syncutil/singleflight/singleflight.go:56 +0x196
perkeep.org/pkg/cacher.(*CachingFetcher).faultIn(0xc0001d2a40, 0x0, 0x0, 0xa1d100, 0xc000038180, 0x0, 0x0)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/cacher/cacher.go:84 +0xcb
perkeep.org/pkg/cacher.(*CachingFetcher).Fetch(0xc0001d2a40, 0x0, 0x0, 0xa1d100, 0xc000038180, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/cacher/cacher.go:77 +0x20d
perkeep.org/pkg/schema.staticSet(0x0, 0x0, 0xa1d100, 0xc000038180, 0xa12160, 0xc0001b46e0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/schema/dirreader.go:105 +0xaf
perkeep.org/pkg/schema.(*DirReader).StaticSet(0xc00004c300, 0x0, 0x0, 0xc000100800, 0x0, 0xc0000bd978, 0x40faf8, 0x38)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/schema/dirreader.go:96 +0x89
perkeep.org/pkg/schema.(*DirReader).Readdir(0xc00004c300, 0x0, 0x0, 0xffffffffffffffff, 0xa1d100, 0xc0001223e0, 0xc00004c300, 0x0, 0x0)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/schema/dirreader.go:147 +0x5a
perkeep.org/pkg/fs.(*node).ReadDirAll(0xc0001487e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/fs/fs.go:266 +0x465
perkeep.org/pkg/fs.(*node).Lookup(0xc0001487e0, 0xa1aa18, 0xc00004c2c0, 0xc000126da4, 0x4, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.w6aamWQDqh/perkeep/pkg/fs/fs.go:153 +0x2a5
bazil.org/fuse/fs.(*Server).handleRequest(0xc000136000, 0xa1aa18, 0xc00004c2c0, 0xa12240, 0xc0001487e0, 0xc00012c540, 0xa198d0, 0xc00012c600, 0xc0000bdeb0, 0xa1d100, ...)
	/home/user/go/pkg/mod/bazil.org/fuse@v0.0.0-20180421153158-65cc252bf669/fs/serve.go:1048 +0x31b2
bazil.org/fuse/fs.(*Server).serve(0xc000136000, 0xa198d0, 0xc00012c600)
	/home/user/go/pkg/mod/bazil.org/fuse@v0.0.0-20180421153158-65cc252bf669/fs/serve.go:878 +0x419
bazil.org/fuse/fs.(*Server).Serve.func1(0xc000136000, 0xa198d0, 0xc00012c600)
	/home/user/go/pkg/mod/bazil.org/fuse@v0.0.0-20180421153158-65cc252bf669/fs/serve.go:425 +0x6f
created by bazil.org/fuse/fs.(*Server).Serve
	/home/user/go/pkg/mod/bazil.org/fuse@v0.0.0-20180421153158-65cc252bf669/fs/serve.go:423 +0x354
```

Is there any way I can provide more debug information or otherwise help with the diagnosis? Is this reproducible for you?

Thank you

**Comment by MichaHoffmann** [comment]
This nil context gets populated down here:

https://github.com/perkeep/perkeep/blob/46e4e4f9e791a8304ff96ac71d041b30d4a031aa/pkg/fs/fs.go#L153

Looks to me as if passing the context into that function was just forgotten!
