### ISSUE TITLE
Reindexing succeeded, or failed?

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#954]
My reindex from https://github.com/camlistore/camlistore/issues/953#issuecomment-329990046 completed after 11 hours, kinda?

I see conflicting output. I see both:

`Index rebuild complete.`
and
`Error reindexing /index/: 1 blobs failed to re-index`

```
bard:camlistore $ ~/src/camlistore.org/bin/camlistored -configfile ~/.config/camlistore/server-config-leveldb.json -reindex
2017/09/16 12:32:42 Starting camlistored version 2017-09-14-4a8e6f03b5; Go go1.9 (linux/amd64)
2017/09/16 12:32:42 TLS enabled, with SHA-256 certificate fingerprint: 0bd85703c391985ce80a
2017/09/16 12:32:42 Starting to listen on https://127.0.0.1:4430
2017/09/16 12:32:47 Index wiped.
2017/09/16 12:32:47 Reindexing /index/ ...
2017/09/16 12:32:47 Rebuilding index...
2017/09/16 12:32:47 Reindexing at sha1-0000000a84aa1c10c44f0ca9365303d1b329d066
2017/09/16 12:32:48 Non critical TIFF decoding error: loading EXIF sub-IFD: exif: sub-IFD ExifIFDPointer decode failed: zero length tag value
2017/09/16 12:32:48 Invalid EXIF GPS data: loading EXIF sub-IFD: exif: sub-IFD ExifIFDPointer decode failed: zero length tag value
2017/09/16 12:32:48 Reindexing at sha1-0001288a1fd6d546dcf7c8e62d6d93d730c89ed7
2017/09/16 12:32:49 Reindexing at sha1-000160b7656f5a55a6f7db674aa69bce7049eadb
2017/09/16 12:32:51 Reindexing at sha1-0001ddb511af532ce796714875279d859777d27a
2017/09/16 12:32:52 Reindexing at sha1-000225a9f5e6e19565e30eb35a74367697d386f2
2017/09/16 12:32:53 Reindexing at sha1-00022a0b932655b226c7db46349bf418bd7281cd
2017/09/16 12:32:54 Reindexing at sha1-000262a180a6ed57692a96bb4a0994b91800f8ae
2017/09/16 12:32:56 Reindexing at sha1-00029744e879ad332145545c0e5f86cd251b1c11
2017/09/16 12:32:58 Reindexing at sha1-0002a54a18ca09c4b99d3adf39a25c5836b25cd7
2017/09/16 12:33:00 Reindexing at sha1-0002c1192b8325ffc7622768d1e51417f11fc3cc
2017/09/16 12:33:02 Reindexing at sha1-0002ea2cada410de8bd3cd958194349a3aca35ea
2017/09/16 12:33:05 Reindexing at sha1-0002fc0541307ed49bd2bd294c96675b85231f80
2017/09/16 12:33:07 Reindexing at sha1-00032a34aeb5c267c79e3835d78e4266d12365a8
2017/09/16 12:33:08 Reindexing at sha1-0003583c2e316d99989db9ee05e781f51cd858b5
....
....
2017/09/16 23:25:34 Reindexing at sha1-ffe90aaa60499b433464c8cc24b900c3e0ae25f6
2017/09/16 23:25:35 Reindexing at sha1-ffebe8aeadc5e9ace846ec94425e124bbf213a50
2017/09/16 23:25:36 Reindexing at sha1-fff09087759b6fdb234798a6c717a38aead3bc07
2017/09/16 23:25:37 Reindexing at sha1-fff581a041837467f662e8cb09c7386d98fcf0f7
2017/09/16 23:25:38 Reindexing at sha1-fff8b9ba485139dbf47f9a242422c09af97af8d0
2017/09/16 23:25:40 Reindexing at sha1-fffb06155ee6adc30c7f71bb0cd6f0de9910aec0
2017/09/16 23:25:41 Reindexing at sha1-fffea6738f2a2115e1f6e82538ff4c669282e1e7
2017/09/16 23:25:41 Index rebuild complete.
2017/09/16 23:25:41 Caught panic installer handlers: Error reindexing /index/: 1 blobs failed to re-index
goroutine 1 [running]:
runtime/debug.Stack(0xc42008e190, 0x2, 0xc424a8b860)
        /home/bradfitz/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /home/bradfitz/go/src/runtime/debug/stack.go:16 +0x22
camlistore.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc4242b7c68)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:540 +0xa8
panic(0xe92420, 0xc420a3be20) 
        /home/bradfitz/go/src/runtime/panic.go:491 +0x283 
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc42069fcb0, 0xc420395a80, 0x10ae863, 0x19)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:308 +0x1a2 
panic(0xe92420, 0xc420a3be20)
        /home/bradfitz/go/src/runtime/panic.go:491 +0x283
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4209e0120, 0xc420395a80, 0x10a291e, 0xe)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0xe92420, 0xc420a3be20)
        /home/bradfitz/go/src/runtime/panic.go:491 +0x283
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4209e01e0, 0xc420395a80, 0x109b7d1, 0x7)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0xe92420, 0xc420a3be20)
        /home/bradfitz/go/src/runtime/panic.go:491 +0x283
camlistore.org/pkg/serverinit.exitFailure(0x10ac79b, 0x17, 0xc4242b69a8, 0x2, 0x2)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:277 +0x16e
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420395a80, 0x109b7d1, 0x7)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:329 +0x917
camlistore.org/pkg/serverinit.(*handlerLoader).GetStorage(0xc420395a80, 0x109b7d1, 0x7, 0x0, 0x1, 0xc420046780, 0x0)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:251 +0x43
camlistore.org/pkg/blobserver/replica.newFromConfig(0x1b819e0, 0xc420395a80, 0xc42069ed20, 0x7, 0xc420035680, 0x42be01, 0xc42015a8a0)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/replica/replica.go:112 +0x269
camlistore.org/pkg/blobserver.CreateStorage(0x10a45b1, 0x7, 0x1b819e0, 0xc420395a80, 0xc42069ed20, 0xe, 0x1, 0x2, 0xf78cc0)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/registry.go:111 +0xc3
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420395a80, 0x10a291e, 0xe)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:321 +0x25c
camlistore.org/pkg/serverinit.(*handlerLoader).GetStorage(0xc420395a80, 0x10a291e, 0xe, 0x1098bc0, 0x4, 0xc4209e03f0, 0x7f87b8ecb668)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:251 +0x43
camlistore.org/pkg/blobserver/cond.buildStorageForReceive(0x1b819e0, 0xc420395a80, 0xf12be0, 0xc42069ed80, 0x0, 0x0, 0x0)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/cond/cond.go:134 +0x167
camlistore.org/pkg/blobserver/cond.newFromConfig(0x1b819e0, 0xc420395a80, 0xc42069edb0, 0x4, 0xc420035660, 0x42be01, 0xc420132120)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/cond/cond.go:90 +0x341
camlistore.org/pkg/blobserver.CreateStorage(0x10a178b, 0x4, 0x1b819e0, 0xc420395a80, 0xc42069edb0, 0x19, 0x0, 0x1, 0xc420000180)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/registry.go:111 +0xc3
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420395a80, 0x10ae863, 0x19)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:321 +0x25c
camlistore.org/pkg/serverinit.(*handlerLoader).setupAll(0xc420395a80)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:231 +0x92
camlistore.org/pkg/serverinit.(*Config).InstallHandlers(0xc4208f28c0, 0x1b6f1e0, 0xc420395680, 0xc420637540, 0x1f, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:609 +0xb7e
main.Main(0x0, 0x0)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:758 +0x4dd
main.main()
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:701 +0x33
Error parsing config: Caught panic: Error reindexing /index/: 1 blobs failed to re-index
 
bard:camlistore $
```

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/11286

**Comment by mpl** [comment]
according to the code, there should also have been a

log.Printf("Error reindexing %v: %v", br, err)

happening. Do you see it in your output?
(so we can fix the actual error, in addition to the wrongly positive log message)

**Comment by mpl** [comment]
@bradfitz is this issue still relevant?

**Comment by bradfitz** [comment]
Probably all fixed now. I'll reopen if I see it be confusing again.
